CREATE PROCEDURE SP_GET_PRODUCTOS
AS
BEGIN
SELECT * FROM PRODUCTOS
WHERE ACTIVO IS NULL
END;

CREATE PROCEDURE SP_DELETE_PRODUCTO
@ID INT
AS
BEGIN
	UPDATE PRODUCTOS
	SET ACTIVO = 0
	WHERE ID_PRODUCTO = @ID
END;