CREATE PROCEDURE SP_GET_OBRAS_SOCIALES
AS
BEGIN
	SELECT ID_OBRASOCIAL, NOMBRE
	FROM OBRA_SOCIAL
	ORDER BY NOMBRE
END;

CREATE PROCEDURE SP_GET_MEDICO
@ID INT
AS
BEGIN
	SELECT M.ID_MEDICO, M.MATRICULA, M.APELLIDO, M.NOMBRE, M.ID_OBRASOCIAL, O.NOMBRE, M.ID_SEDE,
	S.NOMBRE, M.FECHA_INGRESO, M.TELEFONO, M.EMAIL
	FROM MEDICOS M
	JOIN OBRA_SOCIAL O ON O.ID_OBRASOCIAL = M.ID_OBRASOCIAL
	JOIN SEDES S ON S.ID_SEDE = M.ID_SEDE
	WHERE M.ID_MEDICO = @ID
END;

CREATE PROCEDURE SP_DELETE_MEDICO
@ID INT
AS
BEGIN
	DELETE MEDICOS
	WHERE ID_MEDICO = @ID
END;