CREATE PROCEDURE SP_GET_OBRAS_SOCIALES
AS
BEGIN
	SELECT ID_OBRASOCIAL, NOMBRE
	FROM OBRA_SOCIAL
	ORDER BY NOMBRE
END;

CREATE PROCEDURE SP_DELETE_MEDICO
@ID INT
AS
BEGIN
	UPDATE MEDICOS
	SET ACTIVO = 0
	WHERE ID_MEDICO = @ID
END;

CREATE PROCEDURE SP_UPDATE_MEDICO
@ID INT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@OBRA_SOCIAL INT,
@SEDE INT,
@TELEFONO BIGINT,
@EMAIL VARCHAR(50)
AS
BEGIN
	UPDATE MEDICOS SET
	NOMBRE = @NOMBRE, 
	APELLIDO = @APELLIDO, 
	ID_OBRASOCIAL = @OBRA_SOCIAL,
	ID_SEDE = @SEDE, 
	TELEFONO = @TELEFONO, 
	EMAIL = @EMAIL
	WHERE ID_MEDICO = @ID
END;


CREATE PROCEDURE SP_INSERT_MEDICO
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@OBRA_SOCIAL INT,
@SEDE INT,
@TELEFONO BIGINT,
@EMAIL VARCHAR(50),
@MATRICULA INT
AS
BEGIN
	INSERT INTO MEDICOS(ID_MEDICO,NOMBRE, APELLIDO, ID_OBRASOCIAL, ID_SEDE, TELEFONO,
	EMAIL, MATRICULA, FECHA_INGRESO)
	VALUES((SELECT MAX(ID_MEDICO) + 1 FROM MEDICOS), @NOMBRE, @APELLIDO, @OBRA_SOCIAL,
	@SEDE, @TELEFONO, @EMAIL, @MATRICULA, GETDATE())
END;
