CREATE PROCEDURE SP_GET_OBRAS_SOCIALES
AS
BEGIN
	SELECT ID_OBRASOCIAL, NOMBRE
	FROM OBRA_SOCIAL
	ORDER BY NOMBRE
END;

CREATE PROCEDURE SP_GET_MEDICO
@ID INT
AS
BEGIN
	SELECT M.ID_MEDICO, M.MATRICULA, M.APELLIDO, M.NOMBRE, M.ID_OBRASOCIAL, O.NOMBRE, M.ID_SEDE,
	S.NOMBRE, M.FECHA_INGRESO, M.TELEFONO, M.EMAIL
	FROM MEDICOS M
	JOIN OBRA_SOCIAL O ON O.ID_OBRASOCIAL = M.ID_OBRASOCIAL
	JOIN SEDES S ON S.ID_SEDE = M.ID_SEDE
	WHERE M.ID_MEDICO = @ID
END;

CREATE PROCEDURE SP_DELETE_MEDICO
@ID INT
AS
BEGIN
	DELETE MEDICOS
	WHERE ID_MEDICO = @ID
END;


CREATE PROCEDURE SP_UPDATE_MEDICO
@ID INT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@OBRA_SOCIAL INT,
@SEDE INT,
@TELEFONO BIGINT,
@EMAIL VARCHAR(50),
@MATRICULA INT,
@FECHA_INGRESO DATE
AS
BEGIN
	UPDATE MEDICO SET
	@NOMBRE = @NOMBRE, 
	APELLIDO = @APELLIDO, 
	ID_OBRASOCIAL = @OBRA_SOCIAL,
	ID_SEDE = @SEDE, 
	TELEFONO = @TELEFONO, 
	EMAIL = @EMAIL, 
	MATRICULA = @MATRICULA, 
	FECHA_INGRESO = @FECHA_INGRESO
	WHERE ID_MEDICO = @ID
END;


CREATE PROCEDURE SP_INSERT_MEDICO
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@OBRA_SOCIAL INT,
@SEDE INT,
@TELEFONO BIGINT,
@EMAIL VARCHAR(50),
@MATRICULA INT,
@FECHA_INGRESO DATE
AS
BEGIN
	INSERT INTO MEDICOS(ID_CLIENTE,NOMBRE, APELLIDO, ID_OBRASOCIAL, ID_SEDE, TELEFONO,
	EMAIL, MATRICULA, FECHA_INGRESO)
	VALUES((SELECT MAX(ID_CLIENTE) + 1 FROM MEDICOS), @NOMBRE, @APELLIDO, @OBRA_SOCIAL,
	@SEDE, @TELEFONO, @EMAIL, @MATRICULA, @FECHA_INGRESO)
END;
