
--SP DE COMPRAS DE PRODUCTO

CREATE PROCEDURE SP_FACTURACION_PRODUCTO
@id INT
AS 
BEGIN
	SELECT * from PRODUCTOS P
	left join  tipos_productos tp on p.ID_T_PRODUCTO = tp.ID_T_PRODUCTO 
	where p.ID_PRODUCTO = @id
END;

-- SP DE SERVICIOS

CREATE PROCEDURE SP_GET_SERVICIOS
AS
BEGIN
	SELECT ID_SERVICIO, SERVICIO 
	FROM SERVICIOS
	ORDER BY SERVICIO
END;

CREATE PROCEDURE SP_GET_MEDICOS
AS
BEGIN
	SELECT M.ID_MEDICO, M.MATRICULA, M.APELLIDO, M.NOMBRE, M.ID_OBRASOCIAL, O.NOMBRE, M.ID_SEDE,
	S.NOMBRE, M.FECHA_INGRESO, M.TELEFONO, M.EMAIL
	FROM MEDICOS M
	JOIN OBRA_SOCIAL O ON O.ID_OBRASOCIAL = M.ID_OBRASOCIAL
	JOIN SEDES S ON S.ID_SEDE = M.ID_SEDE
	WHERE ACTIVO IS NULL OR ACTIVO = 1
END;

--SP DE FACTURACION FINAL

CREATE PROCEDURE SP_GET_SEDES
AS
BEGIN
	SELECT ID_SEDE, NOMBRE 
	FROM SEDES
	ORDER BY NOMBRE
END;

CREATE PROCEDURE SP_GET_EMPLEADOS_X_SEDE
@SEDE INT
AS
BEGIN
	SELECT LEGAJO, NOMBRE, APELLIDO
	FROM EMPLEADOS
	WHERE ID_SEDE = @SEDE AND
	WHERE ACTIVO IS NULL OR ACTIVO = 1
	ORDER BY APELLIDO
END;

CREATE PROCEDURE SP_GET_FORMA_PAGO
AS
BEGIN
	SELECT ID_PAGO, PAGO 
	FROM FORMA_PAGO
	ORDER BY PAGO
END;

CREATE PROCEDURE SP_GET_FORMA_ENVIO
AS
BEGIN
	SELECT ID_ENVIO, ENVIO 
	FROM FORMA_ENVIO
	ORDER BY ENVIO
END;

CREATE PROCEDURE SP_INSERT_FACTURAS
@LEGAJO INT,
@CLIENTE INT,
@PAGO INT,
@SEDE INT,
@ENVIO INT,
@FACTURA INT OUTPUT
AS
BEGIN

SELECT @FACTURA = (MAX(NRO_FACTURA) +1) FROM FACTURAS

INSERT INTO FACTURAS(NRO_FACTURA, FECHA,LEGAJO, ID_CLIENTE,ID_PAGO, ID_SEDE, ID_ENVIO)
VALUES(@FACTURA, GETDATE(), @LEGAJO, @CLIENTE,@PAGO, @SEDE, @ENVIO)

END;

CREATE PROCEDURE SP_INSERT_DET_SERVICIO
@FACTURA INT,
@MEDICO INT,
@SERVICIO INT,
@PRECIO DECIMAL(10,2),
@ATENCION INT,
@DESCUENTO INT
AS
BEGIN
	INSERT INTO DETALLE_SERVICIO (ID_DET_SERV, NRO_FACTURA, ID_MEDICO, ID_SERVICIO, PRECIO, ATENCION, DESCUENTO)
	VALUES ((SELECT MAX(ID_DET_SERV) + 1 FROM DETALLE_SERVICIO),@FACTURA,@MEDICO,@SERVICIO,@PRECIO,@ATENCION, @DESCUENTO)
END;

CREATE PROCEDURE SP_INSERT_DET_FACTURA
@FACTURA INT,
@PRODUCTO INT,
@CANTIDAD INT,
@PRECIO DECIMAL(10,2)
AS
BEGIN
	INSERT INTO DETALLE_FACTURA(ID_DET_FACT, NRO_FACTURA, ID_PRODUCTO, CANTIDAD,PRECIO)
	VALUES ((SELECT MAX(ID_DET_FACT) + 1 FROM DETALLE_FACTURA),@FACTURA,@PRODUCTO,@CANTIDAD,@PRECIO)
END;
