--VERIFICAR FACTURA

SELECT TOP 1 F.NRO_FACTURA 'FACTURA', F.FECHA 'FECHA', 
E.NOMBRE +' '+ E.APELLIDO 'EMPLEADO', C.NOMBRE +' '+ C.APELLIDO 'CLIENTE', 
PA.PAGO 'PAGO', S.NOMBRE 'SEDE', EN.ENVIO 'ENVIO'
FROM FACTURAS F
JOIN CLIENTES C ON C.ID_CLIENTE = F.ID_CLIENTE
JOIN EMPLEADOS E ON E.LEGAJO = F.LEGAJO
JOIN FORMA_PAGO PA ON PA.ID_PAGO = F.ID_PAGO
JOIN FORMA_ENVIO EN ON EN.ID_ENVIO = F.ID_ENVIO
JOIN SEDES S ON S.ID_SEDE = F.ID_SEDE
ORDER BY F.NRO_FACTURA DESC

-- VERIFICAR DETALLE FACTURA

SELECT D.ID_DET_FACT 'ID', F.NRO_FACTURA 'FACTURA', P.NOMBRE 'PRODUCTO', D.CANTIDAD 'CANTIDAD', D.PRECIO 'PRECIO' FROM DETALLE_FACTURA D
JOIN PRODUCTOS P ON P.ID_PRODUCTO = D.ID_PRODUCTO
JOIN FACTURAS F ON F.NRO_FACTURA = D.NRO_FACTURA
WHERE F.NRO_FACTURA = ( SELECT TOP 1 NRO_FACTURA FROM FACTURAS ORDER BY NRO_FACTURA DESC )

--VERIFICAR DETALLE SERVICIO

SELECT D.ID_DET_SERV 'ID', F.NRO_FACTURA 'FACTURA', M.APELLIDO +' '+ M.NOMBRE 'MEDICO', S.SERVICIO 'SERVICIO', D.PRECIO 'PRECIO', D.ATENCION 'ATENCION'
FROM DETALLE_SERVICIO D
JOIN FACTURAS F ON F.NRO_FACTURA = D.NRO_FACTURA
JOIN SERVICIOS S ON S.ID_SERVICIO = D.ID_SERVICIO
JOIN MEDICOS M ON M.ID_MEDICO = D.ID_MEDICO
WHERE F.NRO_FACTURA = ( SELECT TOP 1 NRO_FACTURA FROM FACTURAS ORDER BY NRO_FACTURA DESC )